name: weather_flutter
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_icons: ^0.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  fonts:
    - family: NexaRegular
      fonts:
        - asset: assets/fonts/NexaRegular.otf
    - family: NexaBold
      fonts:
        - asset: assets/fonts/NexaBold.otf
    - family: NexaLight
      fonts:
        - asset: assets/fonts/NexaLight.otf
    - family: NexaThin
      fonts:
        - asset: assets/fonts/NexaThin.otf